spring:
  datasource:
    url: jdbc:mysql://106.15.228.79:3306/laoshanvipmsdb?serverTimezone=UTC
    username: root
    password: njls6789
    driver-class-name: com.mysql.cj.jdbc.Driver

# 之后的填写mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
