spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC
    username: root
    password: 11100064heqi
    driver-class-name: com.mysql.cj.jdbc.Driver

# 之后的填写mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082
#  servlet:
#    context-path: /api
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
